networks:
  product-network:

services:
  product-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: product-client
    networks:
      - product-network
    depends_on:
      - product-server
    ports:
      - 5173:5173
    volumes:
      - ./client:/code
      - /code/node_modules 
    environment:
      - VITE_BASE_URL=http://ap-server:9000/api
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  product-server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=20
        - ENVIRONMENT=development
    container_name: product-server
    networks:
      - product-network
    depends_on:
      - product-mongo
    ports:
      - 9000:9000
    volumes:
      - ./server/src:/code/src
    environment:
      - PORT=9000
      - MONGO_URI=mongodb://root:example@product-mongodb:27017/
      - MONGO_DB=product-db

  product-mongo:
    image: mongo
    container_name: product-mongodb
    networks:
      - product-network
    ports:
      - 27017:27017
    volumes:
      - ./.mongo-data/data:/data/db
      - ./.mongo-data/config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
